# Generated by Django 5.1.3 on 2024-11-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outflows',
            new_name='Outflow',
        ),
    ]
