# Generated by Django 4.2.20 on 2025-06-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airesult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
